version: '3.8'

services:
  web:
    command: /venv/bin/python3 -m debugpy --listen 0.0.0.0:8002 --wait-for-client manage.py runserver 0.0.0.0:8001 --noreload
    ports:
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./:/app
    environment:
      ENABLE_DEBUG: "True"
    depends_on:
      - db