# Generated by Django 5.2 on 2025-04-03 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="todo",
            name="user_id",
            field=models.CharField(
                default=2, max_length=255, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo", name="id", field=models.CharField(max_length=100),
        ),
    ]
